#! /usr/bin/env python3

import sys, time

if len(sys.argv) < 2:
    sys.stderr.write("epochtime <file to append> <marker name>")
    sys.exit(1)

with open(sys.argv[1], "a+") as myfile:
    myfile.write("%f %s\n" % (time.time(), sys.argv[2]))
